---
- hosts: freebsd
  roles:
    - ports_pkgng
#- hosts: bastion
#  become: yes
#  roles:
#    - bastion
- hosts: ssh
  become: yes
  roles:
    - users
  include_vars:
    file: vars/users.yml
    name: users
- hosts: ssh
  become: yes
  roles:
    - sudoers
  vars:
    sudo_defaults:
      - defaults: env_reset
      - defaults: secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    sudo_users:
      - name: '%wheel'
        nopasswd: yes
    sudo_sudoers_d_path: /usr/local/etc/sudoers.d
#- hosts: bastion
#  become: yes
#  roles:
#    - bastion
#- hosts: webserver
#  become: yes
#  roles:
#    - webserver
#- hosts: workstation
#  become: yes
#  roles:
#    - workstation
