---
- hosts: freebsd
  become: yes
  roles:
    - ports_pkgng
- hosts: ssh
  become: yes
  roles:
    - users
  vars_files:
    - vars/users.yml
- hosts: ssh
  become: yes
  roles:
    - sudoers
  vars_files:
    - vars/sudoers.yml
- hosts: freebsd
  become: yes
  roles:
    - pkg_install
  vars_files:
    - vars/always_install.yml
- hosts: workstation
  become: yes
  roles:
    - pkg_install
  vars_files:
    - vars/workstation_install.yml
#- hosts: bastion
#  become: yes
#  roles:
#    - bastion
#- hosts: webserver
#  become: yes
#  roles:
#    - webserver
#- hosts: workstation
#  become: yes
#  roles:
#    - workstation
