---
- hosts: freebsd
  roles:
    - ports_pkgng
#- hosts: bastion
#  become: yes
#  roles:
#    - bastion
- hosts: ssh
  become: yes
  roles:
    - users
  vars:
    - include: vars/users.yml
- hosts: ssh
  become: yes
  roles:
    - sudoers
  vars:
    - include: vars/sudoers.yml
#- hosts: bastion
#  become: yes
#  roles:
#    - bastion
#- hosts: webserver
#  become: yes
#  roles:
#    - webserver
#- hosts: workstation
#  become: yes
#  roles:
#    - workstation
