---
# tasks file for pkg_install
- name: Install packages
  include_tasks: install.yml
  with_items: {{include_packages}}
- name: Remove packages
  include_tasks: deinstall.yml
  with_items: {{exclude_packages}}
