---
- name: pkg db check
  stat:
    path: /var/db/pkg/local.sqlite
  register: pkg_db_state
- name: pkg sanity check
  shell: pkg -N
  ignore_errors: yes
  register: pkg_state
- name: make ports-mgmt/pkg
  shell: make -C /usr/ports/ports-mgmt/pkg -DBATCH install clean
  when: pkg_db_state.stat.exists == False or pkg_state.rc == 0
