---

- name: pkg db check
  stat:
    path: /var/db/pkg/local.sqlite
  register: pkg_db_state
- name: false
  shell: false
  register: false
- name: pkg sanity check
  shell: pkg -N
  register: pkg_state
  when: false.rc == 0