---

- name: pkg db check
  stat:
    path: /var/db/pkg/local.sqlite
  register: pkg_db_state
- name: check if false
  shell: 'false'
  ignore_errors: yes
  register: false_check
- name: pkg sanity check
  shell: pkg -N
  register: pkg_state
  when: false_check.rc == 0