---
- name: ports git check
  stat:
    path: /usr/ports/.git
  register: git_state
- name: portsnap statefile check
  stat:
    path: /var/ansible/state/portsnap/{{ ansible_date_time.date }}
  register: portsnap_state
- name: git pull
  git:
    repo: https://github.com/freebsd/freebsd-ports
    dest: /usr/ports
  when: git_state.stat.exists == True
- name: portsnap update
  block:
    - name: portsnap statefile dir
      file:
        path: /var/ansible/state/portsnap
        state: directory
        mode: '0700'
        owner: root
        group: wheel
    - name: portsnap fetch
      shell: portsnap fetch >> /var/ansible/state/portsnap/{{ ansible_date_time.date }}.tmp
      register: portsnap_fetch
    - name: portsnap extract
      shell: portsnap extract >> /var/ansible/state/portsnap/{{ ansible_date_time.date }}.tmp
      register: portsnap_extract
      when: portsnap_fetch.rc == 0
    - name: save statefile
      shell: mv /var/ansible/state/portsnap/{{ ansible_date_time.date }}.tmp /var/ansible/state/portsnap/{{ ansible_date_time.date }}
      when: portsnap_fetch.rc == 0 and portsnap_extract.rc == 0
  when: git_state.stat.exists == False and portsnap_state.stat.exists == False
- block:
    - name: lookup ports options
      debug: msg={{ lookup('fileglob', '../../files/var/db/ports/*') }}
    - name: copy ports options
      copy:
        src: '{{ item }}'
        dest: /var/db/ports/
        owner: root
      with_fileglob:
        - ../../files/var/db/ports/*
- name: install portmaster
  portinstall:
    name: ports-mgmt/portmaster
    state: present
